# Generated by Django 3.2.14 on 2022-12-11 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
